# configure python mirror
python-install-mirror = "https://mirrors.nju.edu.cn/github-release/astral-sh/python-build-standalone/" 

# configure pypi mirror
[[index]]
name = "pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

